.TH VHFFS\-MAKEADMIN 1
.SH NAME
vhffs\-userinfo \- Give VHFFS admin status to the specified user
.SH SYNOPSIS
.B vhffs\-makeadmin [username]
.SH "DESCRIPTION"
.B vhffs\-userinfo
give admin status to the user given in parameter. If the user does not exists, die with an error message.
.SH "SEE ALSO"
http://www.vhffs.org
.SH AUTHOR
vhffs-userinfo was written by Sebastien Le Ray <beuss@tuxfamily.org>


