.TH VHFFS\-USERINFO 1
.SH NAME
vhffs\-userinfo \- Print informations about user(s)
.SH SYNOPSIS
.B vhffs\-userinfo [username]
.SH "DESCRIPTION"
.B vhffs\-userinfo
print informations about the user given in parameter. It print all informations about all users who have a name like it.
.SH "SEE ALSO"
http://www.vhffs.org
.SH AUTHOR
vhffs-userinfo was written by Julien Delange <julien@gunnm.org>



