.TH TUXSHELL 1
.SH NAME
Tuxshell \- VHFFS shell
.SH SYNOPSIS
.B tuxshell
.SH "DESCRIPTION"
.B tuxshell
is a shell which prevent to execute any command execpt some
.PP
Tuxshell was written to allow programs like subversion or cvs through ssh but prevent shell connexions.

.SH "SEE ALSO"
http://www.vhffs.org
.SH AUTHOR
Tuxshell was written by Julien Delange <julien@gunnm.org>



