.TH WEBDIR 1
.SH NAME
Webdir \- Shell in a virtualhost directory
.SH SYNOPSIS
.B webdir servername
.SH "DESCRIPTION"
.B webdir
is an utility for vhffs to get a new shell in the directory of a website.
It's easier to go in a directory for a virtualhost.
.SH "SEE ALSO"
http://www.vhffs.org
.SH AUTHOR
Webdir was written by Julien Delange <julien@gunnm.org>



